version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: sh-for-codedeploy/before.sh
      runas: root
  AfterInstall:
    - location: sh-for-codedeploy/after.sh
      runas: root
