version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server
hooks:
  BeforeInstall:
    - location: ./before.sh
      runas: root
  AfterInstall:
    - location: ./after.sh
      runas: root
