version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/src
permissions:
  - object: /home/ubuntu/src
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: ./before.sh
      runas: root
  AfterInstall:
    - location: ./after.sh
      runas: root
