name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: Check Node v
        run: node -v
      - name: Install client Dependencies
        run: npm i
        working-directory: client
      - name: Build
        run: npm run build
        working-directory: client
      - name: create client zip
        run: zip -qq -r ./client.zip ./client
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./client.zip s3://new-words-wiki/new-words-wiki/client.zip
      - name: Deploy
        run: aws deploy create-deployment
          --application-name new-words-wiki
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name new-words-wiki-client
          --s3-location bucket=new-words-wiki,key=new-words-wiki/client.zip,bundleType=zip
