name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: Install client Dependencies
        run: yarn install
        working-directory: src/client
      - name: Install server Dependencies
        run: yarn install
        working-directory: src/server
      - name: Create SERVER env file
        run: |
          touch .env

          echo LOCALHOST=${{ secrets.SERVER_DOT_ENV_LOCALHOST }} >> .env
          echo PORT=${{ secrets.SERVER_DOT_ENV_PORT }} >> .env
          echo MONGO_URI=${{ secrets.SERVER_DOT_ENV_MONGO_URI }} >> .env
          echo DEV_MONGO_URI=${{ secrets.SERVER_DOT_ENV_DEV_MONGO_URI }} >> .env

          echo EMAIL=${{ secrets.SERVER_DOT_ENV_MAIL_ADDRESS }} >> .env
          echo PASS=${{ secrets.SERVER_DOT_ENV_MAIL_PASS }} >> .env

          echo CLIENT_ID=${{ secrets.SERVER_DOT_ENV_GAPI_CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.SERVER_DOT_ENV_GAPI_CLIENT_SECRET }} >> .env
          echo REFRESH_TOKEN=${{ secrets.SERVER_DOT_ENV_GAPI_REFRESH_TOKEN }} >> .env

          echo JWT_SECRET=${{ secrets.SERVER_DOT_ENV_JWT_SECRET }} >> .env

          cat .env
        working-directory: src/server
      - name: Create CLIENT env file
        run: |
          touch .env

          echo NEXT_PUBLIC_DB_URL=${{ secrets.CLIENT_DOT_ENV_DB_URL }} >> .env

          cat .env
        working-directory: src/client
      - name: Build
        run: npm run build
        working-directory: src/client
      - name: create zip
        run: zip -qq -r ./src.zip ./src
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./src.zip s3://new-words-wiki/new-words-wiki/src.zip
      - name: Deploy
        run: aws deploy create-deployment
          --application-name new-words-wiki
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name new-words-wiki-client
          --s3-location bucket=new-words-wiki,key=new-words-wiki/src.zip,bundleType=zip
